version: '3.8'
services:
  mysql:
    container_name: meu_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root
      MYSQL_DATABASE: nome_do_banco
      MYSQL_USER: usuario_do_banco
      MYSQL_PASSWORD: senha_do_usuario
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
